---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-vol
  labels:
    app: mysql
spec: 
  containers:
    - name: mysql
      image: mysql:8
      ports:
        - containerPort: 3306
      #     protocol: TCP 
      volumeMounts:
        - name: mysql-vol
          mountPath: /var/lib/mysql  
      env:
            - name: MYSQL_DATABASE
              value: 'nopdb'
            - name: MYSQL_USER
              value: 'nop'
            - name: MYSQL_PASSWORD
              value: 'nop123'
            - name: MYSQL_ROOT_PASSWORD
              value: 'nop123'
  volumes:
    - name: mysql-vol
      persistentVolumeClaim:
        claimName: mysql-pvc