apiVersion: v1
kind: Pod
metadata:
  name: demo-cms
  labels:
    app: demo
spec:
  containers:
    - name: expercon
      image: alpine
      command:
        - sleep
        - 1d
      envFrom:
        - configMapRef:
            name: userinfo-config
        - secretRef:
            name: userinfo-secret
      
