---
apiVersion: v1 
kind: Service
metadata: 
  name: nginxdb-lb-svc
  labels:
    app: nginxdb-lb
spec: 
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP