apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngin-deploy
  labels:
    app: nginx-pod
spec:
  minReadySeconds: 3
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
  template:
    metadata:
      name: nginx-temp
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
              protocol: TCP              
          resources:
            limits:
              memory:
              cpu:
            requests:
              memory:
              cpu:
              
