---
apiVersion: v1 
kind: Service
metadata: 
  name: nginx-svc
  labels:
    app: nginx-svc
spec:
  type: ClusterIP
  selector:
    app: nginxdb
  ports:
    - targetPort: nginxdb-port
      port: 80 
      protocol: TCP   