---
apiVersion: v1 
kind: Service
metadata: 
  name: nginx-svc
  labels:
    app: nginx-svc
spec:
  type: ClusterIP
  selector: nginxdb 
  ports:
    - targetPort: 80
      port: 80 
      protocol: TCP   