---
apiVersion: rbac.authorization.k8s.io/v1 
kind: Role
metadata: 
  name: spark-role
rules:
  - apiGroups: [""] 
    resources: ["pods" ,"configmaps","services"]
    verbs: ["get","watch","list","create","delete","update","patch"] 

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-role
subjects:
  - kind: ServiceAccount
    name: spark
