---
apiVersion: v1
kind: Service
metadata: 
  name: spark-svc-drive
spec:
  clusterIP: None
  type: ClusterIP
  selector:
    app: spark-job
  ports:
    - port: 29413
      protocol: TCP
      targetPort: 29413
