---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-config 
data: 
  spark-defaults.conf:
    spark.master=k8s://B735BFBA985F35AFDE797DC4000F5D27.gr7.eu-west-1.eks.amazonaws.com
    spark.ui.port=4040
    spark.driver.host=spark-svc-drive
    spark.driver.bindAddress=0.0.0.0
    spark.driver.port=29413
    spark.kubernetes.pyspark.pythonVersion=3
    spark.pyspark.python=/usr/bin/python3
    spark.pyspark.driver.python=/usr/bin/python3
    spark.kubernetes.container.image=cnvrg/custom:spark-2.4.4
    spark.kubernetes.namespace=default
    spark.kubernetes.executor.request.cores=1.0
    spark.executor.instances=3  