---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: spark-master
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: spark-job
  template:
    metadata:
      labels: 
        app: spark-job
    spec: 
      serviceAccount: spark
      containers:
        - name: spark-con
          image: ippilirajesh66/apachespark:latest
          args: 
            - '/opt/spark/bin/spark-submit ../examples/src/main/python/py.py 1000000; tail -f /dev/null;'
          command: 
            - /bin/sh
            - -c
          resources: 
            requests:
              cpu: "1.5"
              memory: 2Gi
          volumeMounts: 
            - mountPath: /opt/spark/conf
              name: spark-config
      volumes: 
        - name: spark-config
          configMap:
            name: spark-config
                
