---
apiVersion: v1
kind: Service
metadata: 
  name: nop-lb-svc
  labels:
    app: nop-lb
spec:
  type: LoadBalancer
  selector:
   app: nop
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP 