---
apiVersion: v1
kind: Pod
metadata:
  name: nopdb-pod
  labels:
    app: nopdb
spec:
  containers:
    - name: nopdb-con
      image: mysql:8
      envFrom:
        - secretRef:
          name: nopdb-secret
      volumeMounts:
        - name: nopdb-vol
          mountPath: /var/lib/mysql  
  volumes:
    - name: nopdb-vol
      persistentVolumeClaim:
        claimName: nopdb-pvc        