apiVersion: batch/v1
kind: CronJob
metadata: 
  name: cronjob-demo
  labels:
    app: nginx
spec:
  schedule: '*/3 * * * *'
  jobTemplate:
    metadata:
      labels:
        app: nginx
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            app: nginx
        spec:
          restartPolicy: OnFailure
          containers:
            - name: nginxc0n
              image: alpine
              command:
                - sleep  
                - 10s