apiVersion: vi
kind: Service
metadata:
  name: dp-svc
  labels:
    app: sample-svc
    namespace: prod
spec:
  type: LoadBalance
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
