apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: spc
  name: spc-deployment
spec: 
  minReadySeconds: 2
  replicas: 3
  selector: 
    matchLabels:
      app: spc-svc
  template:
    metadata:
      name: rajesh
      labels:
        app: spc-svc
    spec:
      containers:
        - name: spc-container
          image: ippilirajesh66/spring-petclinic:1.0
          ports:
            - containerPorts: 8080
              protocol: TCP
          
    
