apiVersion: apps/v1
kind: Deployment
metadata: 
  name: spc-deployment
  labels: 
    app: spc-dep
spec: 
  minReadySeconds: 2
  replicas: 3
  selector: 
    matchLabels:
      app: spc
  template:
    metadata:
      name: rajesh
      labels:
        app: spc1
    spec:
      containers:
        - name: spc-container
          image: ippilirajesh66/spring-petclinic:1.0
          ports:
            - containerPorts: 8080
              protocol: TCP
          
    
