apiVersion: apps/v1
kind: Deployment
metadata: 
  name: spc-deployment
  labels: 
    app: spc-dep
spec: 
  minReadySeconds: 2
  replicas: 3
  selector: 
    matchLabels:
      app: spc
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: spc
      labels:
        app: spc1
    spec:
      containers:
        - name: spc-container
          image: ippilirajesh66/spring-petclinic:1.0
          ports:
            - containerPort: 8080
              
          
    
