apiVersion: v1
kind: Service
metadata: 
  name: spcsvc
  labels: 
    app: spc-svc
spec:
  clusterIP: 
  ports:
    name: spcsvc-port
    port: 8080
    protocol: TCP
    targetport: 32000
  selector:
    app: spc-svc
  type: clusterIP      