apiVersion: v1
kind: Service
metadata: 
  name: jenkis-svc
  labels:
    app: jenkins
spec:
  type: ClusterIP
  selector: 
    app: jenkins
  ports:
    - targetPort: 8080
      port: 8080
      protocol: TCP   