apiVersion: v1
kind: Service
metadata:
  name: nodepote-svc
  labels:
    app: nginx-nodeport-svc 
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - nodePort: 32222
      port: 8080
      targetPort: 8080
      protocol: TCP


 