---
apiVersion: v1 
kind: Service
metadata:
  name: nop-svc 
  labels:
    app: nop-svc 
spec:
  type: LoadBalancer
  selector:
    app: nop 
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP      