---
apiVersion: v1 
kind: Pod
metadata:
  name: nopdb
  labels:
    app: mysql 
spec:
  containers:
    - name: nopdb
      image: mysql:8
      env:
        - name: MYSQL_DATABASE
          value: 'nopdb'
        - name: MYSQL_USER
          value: 'nop'
        - name: MYSQL_PASSWORD
          value: 'nop123'
        - name: MYSQL_ROOT_PASSWORD
          value: 'nop123'
      ports:
        - name: nopdbport
          containerPort: 3306
          protocol: TCP