---
apiVersion: v1
kind: Pod
metadata:
  name: init-demo
  labels:
    app: nginx
    purpose: initdemo
spec:
  initContainers:
    - name: init1
      image: alpine
      command:
        - sleep
        - 30s
    - name: init2
      image: alpine
      command:
        - sleep
        - 30s
  containers:
    - name: webserver
      image: nginx:1.25

 
