apiVersion: v1
kind: Pod
metadata:
  name: init-demo
  labels:
    app: nginx
    purpose: initdemo
spec:
  initContainers:
    - name: init-con1
      image: alpine
      command:
        - sleep
        - 30s
    - name: init-con2
      image: alpine
      command:
        - sleep
        - 60s
  containers:
    - name: nginx-con
      image: nginx:1.25

