apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-pod
spec:
  containers:
    - name: webserver
      image: nginx:1.25
      ports:
        - containerPort: 80
          protocol: TPC

    - name: jenkines
      image: jenkines/jenkins:jdk17
      ports:
        - containerPort: 8080
          protocol: TPC
          