apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-pod
spec:
  containers:
    - name: webserver
      image: nginx:1.25
      ports:
        - containerPort: 80
          protocol: TCP

    - name: jenkines
      image: jenkins/jenkins:jdk11
      ports:
        - containerPort: 8080
          protocol: TCP
