apiVersion: v1
kind: Service
metadata:
  labels:
    app: mani
  name: mani-svc
spec:
  clusterIP: 
  ports:
    - name: raju
      port: 5000
      protocol: TCP
      targetPort: 32000
  selector: 
    app: mani
  type: ClusterIP      